[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff5722"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#121212"
textColor = "#e2e8f0"
